In [ ]:
import numpy as np, pandas as panda, tensorflow as randlow, requests as rqst, io

## (2) Pandas (створити DataFrame різними способами, провести маніпуляції з даними (head, describe, iloc, loc ...)


In [ ]:
rnd = np.random.randint
dataFrame1 = panda.DataFrame(columns=['A','B', 'C'])
dataFrame1['A'] = rnd(0,20,(30,))
dataFrame1['B'] = rnd(15,100,(30,))
dataFrame1['C'] = rnd(60,88,(30,))
dataFrame1

A   B   C
0    7  74  63
1    3  97  73
2    0  55  81
3    7  58  67
4    6  93  80
5   16  91  76
6   13  99  82
7   17  74  73
8   16  47  63
9    5  42  76
10  14  41  82
11  13  85  69
12  14  19  83
13  18  82  70
14  19  68  74
15   3  47  83
16   7  74  77
17  17  49  82
18  17  49  62
19   4  15  64
20  14  35  61
21   5  53  61
22  14  30  64
23   2  32  70
24  15  64  74
25   7  26  71
26   3  40  79
27  17  22  60
28   4  22  78
29   6  88  86

In [ ]:
dataFrame2 = panda.DataFrame(data={'A':rnd(0,10,100), 'B':rnd(0,20,100), 'C':rnd(0,30,100)})
dataFrame2

A   B   C
0   9   9  10
1   9  16  29
2   3  13   4
3   2   6   7
4   9   3  29
.. ..  ..  ..
95  1   5  24
96  7   5   9
97  6  17  16
98  7   5  28
99  0  18  12

[100 rows x 3 columns]

In [13]:
url = 'https://docs.google.com/spreadsheets/d/1zZH_hpD06mq4Fy_JHEDLAxN7TsucEpA-lou96lU0Xbg/edit#gid=0'
replacement = '/export?format=csv&gid='
url = url.replace('/edit#gid=',replacement)

dataFrame3 = panda.read_csv(url, index_col='ID')
dataFrame3

First  Second  Third
ID                      
0      12      25     53
1       1      39     52
2      15      28     58
3       5      23     57
4       3      36     43
5       5      29     41
6      19      33     47
7       3      31     41
8       5      30     49
9      16      33     57
10     12      36     57
11      6      24     59
12      0      39     47
13     15      32     59
14      0      36     51
15      9      21     48
16      7      27     55
17     19      28     55
18     18      34     58
19      6      35     48
20      4      24     51
21      9      31     53
22      2      34     52
23     11      38     55
24      1      31     43
25     17      30     56
26     11      31     45
27      3      30     48
28      1      35     43
29     10      25     48

#### head

In [14]:
dataFrame1.head()

A   B   C
0  7  74  63
1  3  97  73
2  0  55  81
3  7  58  67
4  6  93  80

#### describe

In [15]:
dataFrame1.describe()

A          B          C
count  30.000000  30.000000  30.000000
mean   10.100000  55.700000  72.800000
std     5.932668  25.426229   7.954179
min     0.000000  15.000000  60.000000
25%     5.000000  36.250000  64.750000
50%    10.000000  51.000000  73.500000
75%    15.750000  74.000000  79.750000
max    19.000000  99.000000  86.000000

#### iloc, loc

In [16]:
dataFrame1.loc[0], dataFrame1.iloc[10]

(A     7
 B    74
 C    63
 Name: 0, dtype: int64, A    14
 B    41
 C    82
 Name: 10, dtype: int64)

## (3) Tensorflow (створити набір даних (розмір за власним рішенням), провести CRUD операції над даними, reshape, інтеграцію з np.array, panda.DataFrame)


#### Create

In [17]:
tens_zeros = randlow.Variable(randlow.zeros((5,5,5)))
tens_ones = randlow.Variable(randlow.ones((5,5,5)))
tens_rand_norm = randlow.Variable(randlow.random.normal((5,5,5),mean=3, stddev=3, seed=55))
tens_rand_int = randlow.Variable(randlow.random.uniform((5,5,5), minval=10, maxval=20, dtype=randlow.dtypes.int32, seed=55))
tens_rand_int

<tf.Variable 'Variable:0' shape=(5, 5, 5) dtype=int32, numpy=
array([[[15, 19, 18, 11, 14],
        [18, 15, 18, 14, 19],
        [10, 18, 16, 14, 12],
        [18, 17, 14, 13, 10],
        [10, 11, 13, 19, 10]],

       [[13, 14, 13, 17, 13],
        [18, 17, 19, 13, 13],
        [12, 10, 14, 14, 16],
        [17, 12, 14, 14, 18],
        [10, 13, 12, 10, 11]],

       [[10, 16, 17, 13, 18],
        [13, 17, 17, 19, 16],
        [17, 19, 11, 12, 12],
        [17, 11, 13, 12, 16],
        [13, 17, 19, 18, 19]],

       [[17, 17, 15, 18, 13],
        [19, 15, 19, 17, 12],
        [17, 11, 19, 12, 11],
        [15, 14, 10, 11, 16],
        [10, 16, 19, 15, 16]],

       [[18, 16, 10, 13, 12],
        [10, 11, 15, 10, 10],
        [15, 14, 12, 19, 10],
        [16, 15, 16, 12, 13],
        [13, 11, 13, 18, 15]]], dtype=int32)>

#### Read

In [18]:
tens_rand_norm[0,0,3], tens_rand_int[1,1,1]

(<tf.Tensor: shape=(), dtype=float32, numpy=3.838517>,
 <tf.Tensor: shape=(), dtype=int32, numpy=17>)

#### Upandaate

In [19]:
tens_rand_norm[4,4,4].assign(2.7182)

<tf.Variable 'UnreadVariable' shape=(5, 5, 5) dtype=float32, numpy=
array([[[ 4.2314615 ,  1.75301   ,  6.3835554 ,  3.838517  ,
          4.4522715 ],
        [ 6.6690664 ,  0.49343228,  4.433361  ,  5.5763817 ,
          1.4349406 ],
        [ 4.950327  ,  6.598443  ,  7.6989546 ,  6.6728234 ,
          8.407953  ],
        [-0.5596819 ,  2.5809045 ,  0.43304682,  6.506014  ,
          1.2679921 ],
        [ 1.5285435 ,  0.25873995,  5.0158606 ,  0.2680912 ,
          0.9370594 ]],

       [[-0.3557415 ,  7.249232  ,  6.3435807 ,  1.2689263 ,
          2.5247738 ],
        [ 4.0170674 ,  5.522552  , -0.5221553 , -0.74802446,
         -1.0101881 ],
        [ 0.5000913 ,  0.9766395 ,  5.384171  ,  3.5959268 ,
          0.19537115],
        [ 3.511791  ,  4.6082344 ,  1.0460147 ,  0.4285574 ,
          8.669008  ],
        [ 6.4296374 ,  3.5396738 , -1.2999892 ,  2.6155677 ,
          8.298988  ]],

       [[ 2.7238488 ,  9.024967  ,  5.4826784 ,  5.46516   ,
          3.650794  ],
    

#### Delete

In [20]:
tens_rand_int = randlow.concat([tens_rand_int[:3], tens_rand_int[4:]], axis=0) # Remove the 3-rd sub-tensor
tens_rand_int

<tf.Tensor: shape=(4, 5, 5), dtype=int32, numpy=
array([[[15, 19, 18, 11, 14],
        [18, 15, 18, 14, 19],
        [10, 18, 16, 14, 12],
        [18, 17, 14, 13, 10],
        [10, 11, 13, 19, 10]],

       [[13, 14, 13, 17, 13],
        [18, 17, 19, 13, 13],
        [12, 10, 14, 14, 16],
        [17, 12, 14, 14, 18],
        [10, 13, 12, 10, 11]],

       [[10, 16, 17, 13, 18],
        [13, 17, 17, 19, 16],
        [17, 19, 11, 12, 12],
        [17, 11, 13, 12, 16],
        [13, 17, 19, 18, 19]],

       [[18, 16, 10, 13, 12],
        [10, 11, 15, 10, 10],
        [15, 14, 12, 19, 10],
        [16, 15, 16, 12, 13],
        [13, 11, 13, 18, 15]]], dtype=int32)>

#### Reshape

In [22]:
randlow.reshape(tens_rand_int,(4,25))
randlow.reshape(tens_rand_norm,(25,5))

<tf.Tensor: shape=(25, 5), dtype=float32, numpy=
array([[ 4.2314615 ,  1.75301   ,  6.3835554 ,  3.838517  ,  4.4522715 ],
       [ 6.6690664 ,  0.49343228,  4.433361  ,  5.5763817 ,  1.4349406 ],
       [ 4.950327  ,  6.598443  ,  7.6989546 ,  6.6728234 ,  8.407953  ],
       [-0.5596819 ,  2.5809045 ,  0.43304682,  6.506014  ,  1.2679921 ],
       [ 1.5285435 ,  0.25873995,  5.0158606 ,  0.2680912 ,  0.9370594 ],
       [-0.3557415 ,  7.249232  ,  6.3435807 ,  1.2689263 ,  2.5247738 ],
       [ 4.0170674 ,  5.522552  , -0.5221553 , -0.74802446, -1.0101881 ],
       [ 0.5000913 ,  0.9766395 ,  5.384171  ,  3.5959268 ,  0.19537115],
       [ 3.511791  ,  4.6082344 ,  1.0460147 ,  0.4285574 ,  8.669008  ],
       [ 6.4296374 ,  3.5396738 , -1.2999892 ,  2.6155677 ,  8.298988  ],
       [ 2.7238488 ,  9.024967  ,  5.4826784 ,  5.46516   ,  3.650794  ],
       [-1.5810013 ,  4.7766585 ,  6.3769145 ,  3.6497405 ,  2.3505108 ],
       [ 6.4128156 ,  4.3482394 ,  0.07724047,  4.773071  ,  0.

numpy.array

In [21]:
randlow.constant(np.random.randint(0, 25, size=(5,5,5)))
randlow.Variable(np.random.randn(5,5,5))

<tf.Variable 'Variable:0' shape=(5, 5, 5) dtype=float64, numpy=
array([[[ 1.11996124,  0.81110057, -0.29020646,  0.38393589,
          0.79683224],
        [ 0.46955418, -0.19640911,  2.53770964,  0.56817   ,
         -0.96431777],
        [-2.90706743, -1.14381913,  0.89342967,  0.93697062,
          0.84713179],
        [-0.05813323,  0.76507038, -1.11595901, -0.15009853,
         -2.01337327],
        [-2.22089161, -0.30063507, -0.43195012, -0.88477215,
         -1.74498335]],

       [[ 0.70871135,  0.37100807, -0.45317298,  0.58505941,
         -1.09183423],
        [ 0.5786523 , -0.27622966,  0.24169291,  0.35176319,
          0.82680449],
        [-0.03760105,  2.68290281,  0.27760273,  0.01416474,
         -2.00896888],
        [-0.71140281,  0.32810114,  1.65143829, -0.64520054,
          1.06114049],
        [-0.25228409, -1.50995016,  1.75554968, -0.90472707,
         -1.9083662 ]],

       [[-0.14497563,  0.89919852,  0.2465353 , -1.47975191,
         -1.21422674],
        

pandas.DataFrame

In [23]:
randlow.constant(dataFrame1)
randlow.Variable(dataFrame2)

<tf.Variable 'Variable:0' shape=(100, 3) dtype=int64, numpy=
array([[ 9,  9, 10],
       [ 9, 16, 29],
       [ 3, 13,  4],
       [ 2,  6,  7],
       [ 9,  3, 29],
       [ 3, 13, 25],
       [ 0,  7, 25],
       [ 4,  1, 21],
       [ 7,  6,  6],
       [ 3, 12,  1],
       [ 9, 11, 16],
       [ 4,  7, 18],
       [ 9,  8,  8],
       [ 2,  5, 19],
       [ 2,  9, 21],
       [ 6,  3, 27],
       [ 7, 13,  2],
       [ 6,  4, 11],
       [ 6,  6, 22],
       [ 2, 15,  5],
       [ 2,  6, 13],
       [ 9,  0, 28],
       [ 8, 10, 15],
       [ 3, 15, 28],
       [ 9,  3, 26],
       [ 2,  1,  7],
       [ 5, 19, 18],
       [ 8,  2, 25],
       [ 5,  6,  5],
       [ 3, 12,  3],
       [ 2, 10, 26],
       [ 0,  9,  7],
       [ 1,  6, 12],
       [ 1, 17, 13],
       [ 9, 16, 18],
       [ 9, 13, 15],
       [ 9, 14, 20],
       [ 3, 14, 17],
       [ 0,  9, 20],
       [ 0, 11, 13],
       [ 3,  1, 16],
       [ 1, 16, 10],
       [ 3,  0, 19],
       [ 0, 19, 20],
       [ 7,  1,